name: Gradle Build

on:
  workflow_call:
    inputs:
      version_tag:
        required: true
        type: string
    secrets:
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: ./gradlew build -Pversion=${{ inputs.version_tag }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: build-artifacts
        path: build/libs/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        name: build-artifacts
        path: build/libs/

    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
         username: robert1991
         password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg APP_VERSION=${{ inputs.version_tag }} --tag robert1991/docker-update-sensor:${{ inputs.version_tag }}

    - name: Push dev Docker image  
      run: docker push robert1991/docker-update-sensor:${{ inputs.version_tag }}
